FROM dalibo/buildpack:rockylinux8

RUN set -ex; \
    yum -q -y install \
        rpm-build \
        rpm-sign \
        yum-utils \
        python2 \
        python36 \
        python38 \
        python3-virtualenv \
    ; \
    yum clean all ; \
    :

ADD rpmbuild.sh /usr/local/bin/rpmbuild.sh
ENTRYPOINT ["/usr/local/bin/rpmbuild.sh"]
