FROM dalibo/buildpack:rockylinux8

COPY --from=goreleaser/nfpm:v2.43.4 /usr/bin/nfpm /usr/bin/
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/bin/

RUN set -ex; \
    yum -q -y install \
        rpm-build \
        rpm-sign \
        yum-utils \
        python36 \
        python39 \
    ; \
    yum clean all ; \
    :

RUN PIP_BREAK_SYSTEM_PACKAGES=1 pip3.9 --no-cache-dir install uv-build

ADD rpmbuild.sh /usr/local/bin/rpmbuild.sh
ENTRYPOINT ["/usr/local/bin/rpmbuild.sh"]
