FROM dalibo/buildpack:rockylinux9

RUN set -ex; \
    yum -q -y install \
        rpm-build \
        yum-utils \
        python3 \
    ; \
    yum clean all ; \
    :

ADD rpmbuild.sh /usr/local/bin/rpmbuild.sh
ENTRYPOINT ["/usr/local/bin/rpmbuild.sh"]
