FROM dalibo/buildpack:rockylinux9

RUN set -ex; \
    yum -q -y install \
        https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm \
        rpm-build \
        yum-utils \
        python3 \
    ; \
    yum clean all ; \
    :

ADD rpmbuild.sh /usr/local/bin/rpmbuild.sh
ENTRYPOINT ["/usr/local/bin/rpmbuild.sh"]
