FROM dalibo/buildpack:centos7

RUN set -ex; \
    yum -q -y install \
        gcc \
        python36 \
        python36-devel \
        python36-virtualenv \
        rpm-build \
        ruby-devel \
        yum-utils \
    ; \
    yum clean all ; \
    :

ADD rpmbuild.sh /usr/local/bin/rpmbuild.sh
ENTRYPOINT ["/usr/local/bin/rpmbuild.sh"]
