FROM dalibo/buildpack:rockylinux8

ADD rpmbuild.sh /usr/local/bin/rpmbuild.sh
ENTRYPOINT /usr/local/bin/rpmbuild.sh

RUN set -ex; \
    yum -q -y install \
        rpm-build \
        yum-utils \
        python2 \
        python36 \
        python38 \
        python3-virtualenv \
    ; \
    yum clean all ; \
    :
